version: '3.8'
services:
  pg:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9YVN29ir
    ports:
      - '50432:5432'
    volumes: 
      - pg-data:/var/lib/postgresql/data
  app:
    depends_on:
      - pg
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 30033:30033
volumes:
  pg-data: