version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 30033:30033
networks:
  default:
    external:
      name: my-learning-net